version: '3'
services:
  openBTS:
    stdin_open: true
    tty: true
    privileged: true
    container_name: openbts
    image: 'kherney/openbts-n210:master'
    network_mode: host
    volumes:
      - '/openbts_data:/etc/OpenBTS'
    expose:
      - "45060"
    ports:
      - "49300:49300"
      - "45060:45060"
volumes:
  openbts_data:
    driver: local

